#!/bin/bash

NOWEBFILE=/Users/goshng/Documents/Projects/peach/imr/noweb/imr.nw


CPPFILE=( imr.cpp \
          imrRvTree.cpp \
          imrPriorg.cpp \
          imrMultichain.cpp \
          imrChain.cpp \
          imrTree.cpp \
          imrEdge.cpp \
          imrEvent.cpp \
          imrSequence.cpp \
          imrHelp.cpp \
          imrDefault.cpp \
          imrXmlFastsimcoal.cpp \
          imrXmlImrInput.cpp \
          imrXmlImrOutput.cpp \
          imrXmlImrRectree.cpp \
          imrXmlImrEvent.cpp \
          imrCmdLikelihood.cpp \
          imrXml.cpp )
HPPFILE=( imr.h \
          imrCommon.h \
          imrRvTree.h \
          imrRandomVariable.h \
          imrPriorg.h \
          imrMultichain.h \
          imrChain.h \
          imrTree.h \
          imrEdge.h \
          imrEvent.h \
          imrSequence.h \
          imrHelp.h \
          imrDefault.h \
          imrXmlFastsimcoal.h \
          imrXmlImrInput.h \
          imrXmlImrOutput.h \
          imrXmlImrRectree.h \
          imrXmlImrEvent.h \
          imrCmdLikelihood.h \
          imrXml.h \
          imrType.h )

notangle -RCMakeLists.txt $NOWEBFILE > CMakeLists.txt

for f in ${CPPFILE[@]}; do
  notangle -L -R$f $NOWEBFILE > $f
done

for f in ${HPPFILE[@]}; do
  notangle -R$f $NOWEBFILE | cpif $f
done

sed s/IMRBUILDDATETIME/$(date +%y%m%d%H%M%S)/g < imrHelp.cpp > imrHelp.cpp.tmp
mv imrHelp.cpp.tmp imrHelp.cpp
