all : tex/ilmap.pdf

first.pdf : first.tex
	pdflatex first.tex

tex/2-5.pdf : tex/2-5.tex
	pdflatex tex/2-5.tex

tex/2-7.pdf : tex/2-7.tex
	pdflatex tex/2-7.tex

tex/ilmap.pdf : tex/ilmap.tex
	pdflatex tex/ilmap.tex

clean:
	rm *.aux *.log *.pdf

