function global-variable {
  SPECIESFILE=species/$SPECIES

  # Local machine setup
  OUTPUTDIR=$ROOTANALYSISDIR/output
  BASEDIR=$OUTPUTDIR/$SPECIES
  BASERUNANALYSIS=$BASEDIR/run-analysis
  NUMBERDIR=$BASEDIR/$REPETITION
  DATADIR=$NUMBERDIR/data
  IMRDIR=$NUMBERDIR/imr
  FSCDIR=$NUMBERDIR/fsc

  # Cluster machine setup
  CAC_BASEDIR=$CAC_OUTPUTDIR/$SPECIES
  CAC_NUMBERDIR=$CAC_BASEDIR/$REPETITION
  CAC_DATADIR=$CAC_NUMBERDIR/data
  CAC_IMRDIR=$CAC_NUMBERDIR/imr
  CAC_FSCDIR=$CAC_NUMBERDIR/fsc
}

